// <auto-generated />
using System;
using Dahmira_Log.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dahmira_Log.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250617195436_StratLogs")]
    partial class StratLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dahmira_Log.DAL.Model.Log", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("CurrentUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_GetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_HResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_InnerExceptionMesage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_Mesage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ex_StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lvl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
